### ISSUE TITLE
The path to the game's di rectory is incorrect.

### ISSUE THREAD

**Issue by KUKLY** [joelamos/SourceRadio#10]
**** SourceRadio v2016.08.03 ****

Enter the game you're playing. (Options: tf2, csgo, l4d2)
csgo
Exception in thread "main" java.lang.RuntimeException: The path to the game's directory is incorrect.
        at com.joelchristophel.sourceradio.ScriptWriter.writeScripts(ScriptWriter.java:39)
        at com.joelchristophel.sourceradio.Playlist.initialize(Playlist.java:157)
        at com.joelchristophel.sourceradio.Playlist.<init>(Playlist.java:143)
        at com.joelchristophel.sourceradio.Playlist.getInstance(Playlist.java:124)
        at com.joelchristophel.sourceradio.Playlist.main(Playlist.java:93)
C:\Program Files (x86)\SourceRadio>cmd /k
C:\Program Files (x86)\SourceRadio>

steam path -> D:\Program Files (x86)\Steam

**Comment by joelamos** [comment]
Duplicate of #9
