### ISSUE TITLE
Non-default path to game folder. ( Cannot find cfg folder )

### ISSUE THREAD

**Issue by ghost** [joelamos/SourceRadio#16]
Hi again.
I have installed Tf2 to my second hdd ( `D:\` ) and ofc installed all my games too it.
SourceRadio - provided this input; `-g tf2 -f D:\Program Files (x86)\Steam\steamapps\common\Team Fortress 2` ) - does not detect a tf2 install.
How am I meant to provide the `-f` param?

**Comment by ghost** [comment]
Forget this issue existed. I was meant to wrap the directory in quotes. >.>

**Comment by ghost** [comment]
Alrighty.
Sorry for opening and closing shit so fast, but after wrapping the path in quotes ( and added a `\` at the end of the directory ), SourceRadio spits out an error saying that it couldn't find the cfg folder at path
`"D:\Program Files (x86)\Steam\steamapps\common\Team Fortress 2\"cfg\`.
Which, is pretty funny, how the heck did that even happen?
I thought I needed to escape the `\`'s but nope, still happens.
Escaping the `"`'s produces this: `"D:\Programcfg\.`. Which is even funnier lol.

Full output;
```
D:\Program Files (x86)\SourceRadio>java -jar SourceRadio.jar -g tf2 -f "D:\Program Files (x86)\Steam\steamapps\common\Team Fortress 2\"

**** SourceRadio v2017.02.03 ****

java.io.IOException: Error: Failed to find the path to the game's cfg directory.
        at com.joelchristophel.sourceradio.Game.getCfgPath(Game.java:108)
        at com.joelchristophel.sourceradio.ScriptWriter.writeScripts(ScriptWriter.java:39)
        at com.joelchristophel.sourceradio.Playlist.initialize(Playlist.java:172)
        at com.joelchristophel.sourceradio.Playlist.<init>(Playlist.java:158)
        at com.joelchristophel.sourceradio.Playlist.getInstance(Playlist.java:139)
        at com.joelchristophel.sourceradio.Playlist.main(Playlist.java:97)
Caused by: java.io.IOException: Error: The game's expected cfg directory doesn't exist: D:\Program Files (x86)\Steam\steamapps\common\Team Fortress 2"cfg\.
        at com.joelchristophel.sourceradio.Game.getCfgPath(Game.java:104)
        ... 5 more
Error: Could not find a Team Fortress 2 installation.
