### ISSUE TITLE
The path to the game's directory is incorrect

### ISSUE THREAD

**Issue by Lifeismana** [joelamos/SourceRadio#9]
I tried to launch the program with csgo and tf2 but it return this error :
Exception in thread "main" java.lang.RuntimeException: The path to the game's directory is incorrect.
        at com.joelchristophel.sourceradio.ScriptWriter.writeScripts(ScriptWriter.java:39)
        at com.joelchristophel.sourceradio.Playlist.initialize(Playlist.java:157)
        at com.joelchristophel.sourceradio.Playlist.<init>(Playlist.java:143)
        at com.joelchristophel.sourceradio.Playlist.getInstance(Playlist.java:124)
        at com.joelchristophel.sourceradio.Playlist.main(Playlist.java:93)

**Comment by joelamos** [comment]
Do you have CS:GO installed to the default location?

**Comment by Lifeismana** [comment]
Yes, it's install in "C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive"
but not tf2

**Comment by joelamos** [comment]
Try running it with TF2 and using the `-f` [program argument](https://github.com/joelamos/SourceRadio#program-arguments) to specify the location of the game. You can add this command by editing SourceRadio.bat in the SourceRadio install directory.

**Comment by Lifeismana** [comment]
It give me the same error

C:\Program Files (x86)\SourceRadio>cd "C:\Program Files (x86)\SourceRadio\"

C:\Program Files (x86)\SourceRadio>"C:\Program Files\Java\jre1.8.0_101\bin\java.exe" -jar SourceRadio.jar -f "D:\Games\steamapps\common\Team Fortress 2"

**** SourceRadio v2016.08.03 ****

Enter the game you're playing. (Options: tf2, csgo, l4d2)
tf2
Exception in thread "main" java.lang.RuntimeException: The path to the game's directory is incorrect.
        at com.joelchristophel.sourceradio.ScriptWriter.writeScripts(ScriptWriter.java:39)
        at com.joelchristophel.sourceradio.Playlist.initialize(Playlist.java:157)
        at com.joelchristophel.sourceradio.Playlist.<init>(Playlist.java:143)
        at com.joelchristophel.sourceradio.Playlist.getInstance(Playlist.java:124)
        at com.joelchristophel.sourceradio.Playlist.main(Playlist.java:93)

C:\Program Files (x86)\SourceRadio>cmd /k
C:\Program Files (x86)\SourceRadio>

**Comment by joelamos** [comment]
The documentation should be more explicit, but the game directory for TF2 is `Team Fortress 2\tf\` with the trailing backslash. See if that does the trick. Also try specifying `-g`.

**Comment by Lifeismana** [comment]
Okay so actually I'm stupid in properties at the line "steamid3 ->" I wrote my steamid64, not my steamid32 and i have multiple account on that steam so i think that the programs didn't find the good user, but for tf2 it still give me that error : 
C:\Program Files (x86)\SourceRadio>cd "C:\Program Files (x86)\SourceRadio\"

C:\Program Files (x86)\SourceRadio>"C:\Program Files\Java\jre1.8.0_101\bin\java.exe" -jar SourceRadio.jar -f "D:\Games\steamapps\common\Team Fortress 2\tf" -g tf2

**** SourceRadio v2016.08.03 ****

Exception in thread "main" java.lang.RuntimeException: The path to the game's directory is incorrect.
        at com.joelchristophel.sourceradio.ScriptWriter.writeScripts(ScriptWriter.java:39)
        at com.joelchristophel.sourceradio.Playlist.initialize(Playlist.java:157)
        at com.joelchristophel.sourceradio.Playlist.<init>(Playlist.java:143)
        at com.joelchristophel.sourceradio.Playlist.getInstance(Playlist.java:124)
        at com.joelchristophel.sourceradio.Playlist.main(Playlist.java:93)

C:\Program Files (x86)\SourceRadio>cmd /k
C:\Program Files (x86)\SourceRadio>

**Comment by joelamos** [comment]
Note for steamid3 that you need to remove `[U:1:1` and the closing bracket as well. I have a hunch that adding the steaID will fix the problem in CS:GO if it's installed to default.

As I'm looking over my code for supporting custom game paths, it's less than ideal. My next suggestion for TF2 is to set your Steam path as `D:\Games\` (lol) in your properties file and try again.

**Comment by Lifeismana** [comment]
Yeah it's what i mean by steamid32. But settings  Steam path as D:\Games\ don't work because there is no Userdata directory  (Error: Could not find Steam userdata directory: D:\Games\userdata) There is only a "steamapp" folder and a steam.dll file

**Comment by joelamos** [comment]
I tried to delete that portion of my comment before you read it; it was misguided.

**Comment by Lifeismana** [comment]
Ah i didn't reload the page xD

**Comment by joelamos** [comment]
Do you have the directory `tf\cfg`? Also, does it work with CS:GO?

**Comment by Lifeismana** [comment]
Yes I got the directory tf\cfg and it work well with Cs:go

**Comment by joelamos** [comment]
Try to add a trailing backslash after `tf`.

**Comment by Lifeismana** [comment]
Still getting the error:
C:\Program Files (x86)\SourceRadio>cd "C:\Program Files (x86)\SourceRadio\"

C:\Program Files (x86)\SourceRadio>"C:\Program Files\Java\jre1.8.0_101\bin\java.exe" -jar SourceRadio.jar -f "D:\Games\steamapps\common\Team Fortress 2\tf\"

**** SourceRadio v2016.08.03 ****

Enter the game you're playing. (Options: tf2, csgo, l4d2)
tf2
Exception in thread "main" java.lang.RuntimeException: The path to the game's directory is incorrect.
        at com.joelchristophel.sourceradio.ScriptWriter.writeScripts(ScriptWriter.java:39)
        at com.joelchristophel.sourceradio.Playlist.initialize(Playlist.java:157)
        at com.joelchristophel.sourceradio.Playlist.<init>(Playlist.java:143)
        at com.joelchristophel.sourceradio.Playlist.getInstance(Playlist.java:124)
        at com.joelchristophel.sourceradio.Playlist.main(Playlist.java:93)

C:\Program Files (x86)\SourceRadio>cmd /k
C:\Program Files (x86)\SourceRadio>

**Comment by joelamos** [comment]
W was se
